<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateCountriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->increments('id');
            $table->string('title');
            $table->timestamps();
        });
        DB::table('countries')->insert(
            Array(
                ["title"=>"Afghanistan"],
                ["title"=>"Albania"],
                ["title"=>"Algeria"],
                ["title"=>"American Samoa"],
                ["title"=>"Andorra"],
                ["title"=>"Angola"],
                ["title"=>"Anguilla"],
                ["title"=>"Antigua & Barbuda"],
                ["title"=>"Argentina"],
                ["title"=>"Armenia"],
                ["title"=>"Aruba"],
                ["title"=>"Australia"],
                ["title"=>"Austria"],
                ["title"=>"Azerbaijan"],
                ["title"=>"Bahamas, The"],
                ["title"=>"Bahrain"],
                ["title"=>"Bangladesh"],
                ["title"=>"Barbados"],
                ["title"=>"Belarus"],
                ["title"=>"Belgium"],
                ["title"=>"Belize"],
                ["title"=>"Benin"],
                ["title"=>"Bermuda"],
                ["title"=>"Bhutan"],
                ["title"=>"Bolivia"],
                ["title"=>"Bosnia & Herzegovina"],
                ["title"=>"Botswana"],
                ["title"=>"Brazil"],
                ["title"=>"British Virgin Is."],
                ["title"=>"Brunei"],
                ["title"=>"Bulgaria"],
                ["title"=>"Burkina Faso"],
                ["title"=>"Burma"],
                ["title"=>"Burundi"],
                ["title"=>"Cambodia"],
                ["title"=>"Cameroon"],
                ["title"=>"Canada"],
                ["title"=>"Cape Verde"],
                ["title"=>"Cayman Islands"],
                ["title"=>"Central African Rep."],
                ["title"=>"Chad"],
                ["title"=>"Chile"],
                ["title"=>"China"],
                ["title"=>"Colombia"],
                ["title"=>"Comoros"],
                ["title"=>"Congo, Dem. Rep."],
                ["title"=>"Congo, Repub. of the"],
                ["title"=>"Cook Islands"],
                ["title"=>"Costa Rica"],
                ["title"=>"Cote d'Ivoire"],
                ["title"=>"Croatia"],
                ["title"=>"Cuba"],
                ["title"=>"Cyprus"],
                ["title"=>"Czech Republic"],
                ["title"=>"Denmark"],
                ["title"=>"Djibouti"],
                ["title"=>"Dominica"],
                ["title"=>"Dominican Republic"],
                ["title"=>"East Timor"],
                ["title"=>"Ecuador"],
                ["title"=>"Egypt"],
                ["title"=>"El Salvador"],
                ["title"=>"Equatorial Guinea"],
                ["title"=>"Eritrea"],
                ["title"=>"Estonia"],
                ["title"=>"Ethiopia"],
                ["title"=>"Faroe Islands"],
                ["title"=>"Fiji"],
                ["title"=>"Finland"],
                ["title"=>"France"],
                ["title"=>"French Guiana"],
                ["title"=>"French Polynesia"],
                ["title"=>"Gabon"],
                ["title"=>"Gambia, The"],
                ["title"=>"Gaza Strip"],
                ["title"=>"Georgia"],
                ["title"=>"Germany"],
                ["title"=>"Ghana"],
                ["title"=>"Gibraltar"],
                ["title"=>"Greece"],
                ["title"=>"Greenland"],
                ["title"=>"Grenada"],
                ["title"=>"Guadeloupe"],
                ["title"=>"Guam"],
                ["title"=>"Guatemala"],
                ["title"=>"Guernsey"],
                ["title"=>"Guinea"],
                ["title"=>"Guinea-Bissau"],
                ["title"=>"Guyana"],
                ["title"=>"Haiti"],
                ["title"=>"Honduras"],
                ["title"=>"Hong Kong"],
                ["title"=>"Hungary"],
                ["title"=>"Iceland"],
                ["title"=>"India"],
                ["title"=>"Indonesia"],
                ["title"=>"Iran"],
                ["title"=>"Iraq"],
                ["title"=>"Ireland"],
                ["title"=>"Isle of Man"],
                ["title"=>"Israel"],
                ["title"=>"Italy"],
                ["title"=>"Jamaica"],
                ["title"=>"Japan"],
                ["title"=>"Jersey"],
                ["title"=>"Jordan"],
                ["title"=>"Kazakhstan"],
                ["title"=>"Kenya"],
                ["title"=>"Kiribati"],
                ["title"=>"Korea, North"],
                ["title"=>"Korea, South"],
                ["title"=>"Kuwait"],
                ["title"=>"Kyrgyzstan"],
                ["title"=>"Laos"],
                ["title"=>"Latvia"],
                ["title"=>"Lebanon"],
                ["title"=>"Lesotho"],
                ["title"=>"Liberia"],
                ["title"=>"Libya"],
                ["title"=>"Liechtenstein"],
                ["title"=>"Lithuania"],
                ["title"=>"Luxembourg"],
                ["title"=>"Macau"],
                ["title"=>"Macedonia"],
                ["title"=>"Madagascar"],
                ["title"=>"Malawi"],
                ["title"=>"Malaysia"],
                ["title"=>"Maldives"],
                ["title"=>"Mali"],
                ["title"=>"Malta"],
                ["title"=>"Marshall Islands"],
                ["title"=>"Martinique"],
                ["title"=>"Mauritania"],
                ["title"=>"Mauritius"],
                ["title"=>"Mayotte"],
                ["title"=>"Mexico"],
                ["title"=>"Micronesia, Fed. St."],
                ["title"=>"Moldova"],
                ["title"=>"Monaco"],
                ["title"=>"Mongolia"],
                ["title"=>"Montserrat"],
                ["title"=>"Morocco"],
                ["title"=>"Mozambique"],
                ["title"=>"Namibia"],
                ["title"=>"Nauru"],
                ["title"=>"Nepal"],
                ["title"=>"Netherlands"],
                ["title"=>"Netherlands Antilles"],
                ["title"=>"New Caledonia"],
                ["title"=>"New Zealand"],
                ["title"=>"Nicaragua"],
                ["title"=>"Niger"],
                ["title"=>"Nigeria"],
                ["title"=>"N. Mariana Islands"],
                ["title"=>"Norway"],
                ["title"=>"Oman"],
                ["title"=>"Pakistan"],
                ["title"=>"Palau"],
                ["title"=>"Panama"],
                ["title"=>"Papua New Guinea"],
                ["title"=>"Paraguay"],
                ["title"=>"Peru"],
                ["title"=>"Philippines"],
                ["title"=>"Poland"],
                ["title"=>"Portugal"],
                ["title"=>"Puerto Rico"],
                ["title"=>"Qatar"],
                ["title"=>"Reunion"],
                ["title"=>"Romania"],
                ["title"=>"Russia"],
                ["title"=>"Rwanda"],
                ["title"=>"Saint Helena"],
                ["title"=>"Saint Kitts & Nevis"],
                ["title"=>"Saint Lucia"],
                ["title"=>"St Pierre & Miquelon"],
                ["title"=>"Saint Vincent and the Grenadines"],
                ["title"=>"Samoa"],
                ["title"=>"San Marino"],
                ["title"=>"Sao Tome & Principe"],
                ["title"=>"Saudi Arabia"],
                ["title"=>"Senegal"],
                ["title"=>"Serbia"],
                ["title"=>"Seychelles"],
                ["title"=>"Sierra Leone"],
                ["title"=>"Singapore"],
                ["title"=>"Slovakia"],
                ["title"=>"Slovenia"],
                ["title"=>"Solomon Islands"],
                ["title"=>"Somalia"],
                ["title"=>"South Africa"],
                ["title"=>"Spain"],
                ["title"=>"Sri Lanka"],
                ["title"=>"Sudan"],
                ["title"=>"Suriname"],
                ["title"=>"Swaziland"],
                ["title"=>"Sweden"],
                ["title"=>"Switzerland"],
                ["title"=>"Syria"],
                ["title"=>"Taiwan"],
                ["title"=>"Tajikistan"],
                ["title"=>"Tanzania"],
                ["title"=>"Thailand"],
                ["title"=>"Togo"],
                ["title"=>"Tonga"],
                ["title"=>"Trinidad & Tobago"],
                ["title"=>"Tunisia"],
                ["title"=>"Turkey"],
                ["title"=>"Turkmenistan"],
                ["title"=>"Turks & Caicos Is"],
                ["title"=>"Tuvalu"],
                ["title"=>"Uganda"],
                ["title"=>"Ukraine"],
                ["title"=>"United Arab Emirates"],
                ["title"=>"United Kingdom"],
                ["title"=>"United States"],
                ["title"=>"Uruguay"],
                ["title"=>"Uzbekistan"],
                ["title"=>"Vanuatu"],
                ["title"=>"Venezuela"],
                ["title"=>"Vietnam"],
                ["title"=>"Virgin Islands"],
                ["title"=>"Wallis and Futuna"],
                ["title"=>"West Bank"],
                ["title"=>"Western Sahara"],
                ["title"=>"Yemen"],
                ["title"=>"Zambia"],
                ["title"=>"Zimbabwe"]
            )
        );
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('countries');
    }
}
